import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { getCssText } from "@/styles";
import { globalStyles } from "@/styles/global";
import { Container, Header } from "@/styles/pages/app";

import logoImg from "@/assets/logo.svg";

const inter = Roboto({
  subsets: ["latin"],
  style: ["normal"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  globalStyles();
  return (
    <html lang="en">
      <head>
        <style
          id="stitches"
          dangerouslySetInnerHTML={{ __html: getCssText() }}
        />
      </head>
      <body className={inter.className}>
        <Container>
          <Header>
            <img src={logoImg.src} alt="" />
          </Header>
          {children}
        </Container>
      </body>
    </html>
  );
}
